// @ts-nocheck
import { create } from 'zustand'

export interface LectureTime {
  dayOfWeek: number // 0=Sun..6=Sat
  startTime: string // '08:00'
  endTime: string // '09:00'
  location?: string
}

export interface Subject {
  id?: number | string
  name: string
  color: string
  code?: string
  creditHours?: number
  instructor?: string
  lectures?: LectureTime[]
  createdAt: number
}

export interface Task {
  id?: number | string
  title: string
  description?: string
  subjectId?: number | string
  priority: 'high' | 'medium' | 'low'
  dueDate?: number // timestamp
  completed: boolean
  isStudyBlock?: boolean // auto-generated study blocks
  examId?: number | string // link to exam event
  attachments?: any[]
  createdAt: number
  updatedAt: number
}

export interface CalendarEvent {
  id?: number | string
  title: string
  subjectId?: number | string
  type: 'lecture' | 'exam' | 'assignment' | 'study' | 'other'
  startDate: number // timestamp
  endDate: number  // timestamp
  location?: string
  description?: string
  isRecurring?: boolean
  recurringDays?: number[] // 0=Sun..6=Sat
  recurringUntil?: number
  color?: string
  isAutoGenerated?: boolean
  createdAt: number
}

export interface ChatMessage {
  id?: number | string
  role: 'user' | 'assistant'
  content: string
  timestamp: number
  sessionId: string
}

export interface DriveFile {
  id?: number | string
  driveFileId: string
  name: string
  mimeType: string
  size?: number
  subjectId?: number | string
  category?: string
  webViewLink?: string
  thumbnailLink?: string
  modifiedTime?: string
  syncedAt: number
}

export interface ChatSession {
  id: string
  title: string
  createdAt: number
  updatedAt: number
}

interface DataStore {
  subjects: Subject[]
  tasks: Task[]
  events: CalendarEvent[]
  driveFiles: DriveFile[]
  chatSessions: ChatSession[]
  messages: ChatMessage[]

  setSubjects: (data: Subject[]) => void
  setTasks: (data: Task[]) => void
  setEvents: (data: CalendarEvent[]) => void
  setDriveFiles: (data: DriveFile[]) => void
  setChatSessions: (data: ChatSession[]) => void
  setMessages: (data: ChatMessage[]) => void
  whiteboardData: any
  setWhiteboardData: (data: any) => void
}

export const useDataStore = create<DataStore>((set) => ({
  subjects: [],
  tasks: [],
  events: [],
  driveFiles: [],
  chatSessions: [],
  messages: [],

  setSubjects: (data) => set({ subjects: data }),
  setTasks: (data) => set({ tasks: data }),
  setEvents: (data) => set({ events: data }),
  setDriveFiles: (data) => set({ driveFiles: data }),
  setChatSessions: (data) => set({ chatSessions: data }),
  setMessages: (data) => set({ messages: data }),
  whiteboardData: null,
  setWhiteboardData: (data) => set({ whiteboardData: data }),
}))
